addpath(genpath('src'))
addpath('lib/eeglab')
addpath('lib/unfold')
addpath('lib/gramm')
addpath(genpath('lib/SEREEGA'))
addpath('lib/ScientificColourMaps6/')
addpath(genpath('lib/ept_TFCE-matlab'))
eeglab;
init_unfold;
